#!/bin/sh

AVERAGES=()
MEDIANS=()
FILE_LIST=$$"FILE_LIST"
INPUT_FILE="test_file2"
COL_FILE_BASE=$$"col"
ROW_FILE_BASE=$$"row"

touch $FILE_LIST

separate_rows ()
{
    ROW=0
    while read line
    do
        ROW=$(( $ROW + 1 ))

        FILE=$ROW_FILE_BASE$ROW
        touch $FILE
        echo $FILE >> $FILE_LIST

        printf "%s\n" $line > $FILE
    done < $INPUT_FILE
}

separate_columns ()
{
    ROWS=$(wc -l < $INPUT_FILE)
    WORDS=$(wc -w < $INPUT_FILE)
    COLS=$(( 2 * ($WORDS / $ROWS) ))

    for COL in $(seq 1 2 $COLS)
    do
        FILE=$COL_FILE_BASE$COL
        touch $FILE
        echo $FILE >> $FILE_LIST
        cat $INPUT_FILE | cut -c$COL > $FILE
    done
}

sort_files()
{
    while read line
    do
        sort $line -n -o $line
    done < $FILE_LIST
}

calculate_averages()
{
    while read line
    do
        SUM=0
        COUNT=0
        while read -r num
        do
            (( SUM += num ))
            (( COUNT += 1 ))
        done < $line
        AVERAGE=$( echo $SUM / $COUNT + 0.5 | bc -l )
        AVERAGES+=(${AVERAGE%.*})
    done < $FILE_LIST
}

calculate_medians()
{
    while read line
    do
        NUMS=$(wc -l < $line)
        MEDIAN_INDEX=$(( ($NUMS / 2) + 1 ))
        MEDIANS+=($( head -$MEDIAN_INDEX $line | tail -1 ))
    done < $FILE_LIST
}

print_results_rows()
{
    printf "Average\tMedian\n"
    LENGTH=${#AVERAGES[@]}
    for i in "${!AVERAGES[@]}"
    do
        printf '%s\t%s\n' ${AVERAGES[$i]} ${MEDIANS[$i]}
    done
}

print_results_cols()
{
    echo Averages:
    printf "%s\t" "${AVERAGES[@]}"
    printf "\n"
    echo Medians:
    printf "%s\t" "${MEDIANS[@]}"
    printf "\n"
}

clean_up()
{
    rm -f *row*
    rm -f *col*
    rm -f $$"FILE_LIST"
}

common_operations()
{
    sort_files
    calculate_averages
    calculate_medians
}

# get command line args

if [[ $1 == -r* ]];
then
    # separate files into rows **NEEDS ERROR HANDLING**
    separate_rows

    common_operations

    print_results_rows
elif [[ $1 == -c* ]];
then
    # ***DOESNT WORK WITH DOUBLE DIGIT OR TRIPLE DIGIT NUMBERS***

    # separate files into cols ** NEEDS ERROR HANDLING**
    separate_columns

    common_operations

    print_results_cols
fi

# separate into files by row or col !!NEEDS ERROR HANDLING!!
#separate_rows
# separate_columns
# sort files !!NEEDS ERROR HANDLING!!
# sort_files
# calculate average for each file !!NEEDS ERROR HANDLING!!
# calculate_averages
# calculate median for each file !!NEEDS ERROR HANDLING!!
# calculate_medians
# print_results_rows
# print_results_cols

# clean up files
# clean_up

# HANDLE ERRORS
# NEED COMMENTS
# PIPE ERROR OUTPUT CORRECTLY
# CORRECT EXIT STATEMENTS

exit 0
