#!/bin/bash
gcc -o keygen keygen.c
gcc -c server.c
gcc -c client.c
gcc -c utils.c
gcc -c crypto.c
gcc server.o utils.o crypto.o -o otp_enc_d otp_enc_d.c
gcc server.o utils.o crypto.o -o otp_dec_d otp_dec_d.c
gcc client.o utils.o crypto.o -o otp_enc otp_enc.c
gcc client.o utils.o crypto.o -o otp_dec otp_dec.c
